checkpoint_callback:
  mode: max
  monitor: val_acc
  verbose: true
datamodule:
  _type: SVHNToMNISTDataModule
  batch_size: 128
  domain_adaptation: &domain_adaptation true
  num_workers: 8
  train_domains:
  - svhn
  - mnist
hyperparameter_optimization:
  n_trials: 20
  pruninig: True
model:
  _type: SVHNToMNISTModel
  adaptation_factor:
    parameter_space: discrete_uniform
    parameter_space_arguments:
      name: adaptation_factor
      low: 0
      high: 1
      q: 0.01
  domain_adaptation: *domain_adaptation
  lr: 0.001
  use_only_y_labels_from_source_domain: true
seed: 42
trainer:
  max_epochs: 5
