checkpoint_callback:
  mode: max
  monitor: val_acc
  verbose: true
datamodule:
  _type: SVHNToMNISTDataModule
  batch_size: 128
  domain_adaptation: &domain_adaptation true
  num_workers: 8
  train_domains:
  - svhn
  - mnist
model:
  _type: SVHNToMNISTModel
  adaptation_factor: 0.1
  domain_adaptation: *domain_adaptation
  domain_classifier_loss: mse_loss
  gan_style_training: true
  lr: 0.001
  use_only_y_labels_from_source_domain: true
seed: 42
trainer:
  max_epochs: 5
