checkpoint_callback:
  mode: min
  monitor: val_loss
  verbose: True
datamodule:
  datasets:
    - name: WIDERFACE
      weight: 2.0
    - name: FaceMask
      weight: 1.0
  collate:
    grid_h: 2
    grid_w: 2
optimization:
  weight_decay: 0.000001
  start_lr: 0.000001
  max_lr: 0.0005
  end_lr: 0.000001
  base_momentum: 0.95
  max_momentum: 0.85
  pct_start: 0.5
  total_steps: 2000
  grad_clip_percentile: 80
  grad_clip_history_size: 100
trainer:
  precision: 16
  log_every_n_steps: 1
