checkpoint_callback:
  mode: min
  monitor: val_loss
  verbose: True
datamodule:
  datasets:
    - name: widerface
      weight: 2.0
    - name: facemask
      weight: 1.0
  collate:
    grid_h: 1
    grid_w: 1
  batch_size: 48 
optimization:
  weight_decay: 0.000001
  start_lr: 0.000001
  max_lr: 0.0006
  end_lr: 0.000001
  base_momentum: 0.95
  max_momentum: 0.85
  pct_start: 0.5
  total_steps: 6000
  grad_clip_percentile: 80
  grad_clip_history_size: 100
  adaptation_factor: 1.0
trainer:
  precision: 32 
  log_every_n_steps: 1
detector_config:
  config.yaml
