checkpoint_callback:
  mode: min
  monitor: val_loss
  verbose: True
datamodule:
  collate:
    grid_h: 2
    grid_w: 2
optimization:
  optimizer: SGD
  optimizer_config:
    weight_decay: 0.000001
    lr: 1.0
  scheduler: OneCycleLR
  scheduler_config:
    div_factor: 4000
    max_lr: 0.004
    final_div_factor: 4000
    base_momentum: 0.95
    max_momentum: 0.85
    pct_start: 0.5
    total_steps: 25000
  grad_clip_percentile: 80
  grad_clip_history_size: 100
trainer:
  precision: 16
  log_every_n_steps: 1
  max_steps: 24999
